object Versions {

    const val junitVersion = "4.13.2"
    const val junitExtVersion = "1.1.3"
    const val espressoVersion = "3.4.0"
    const val coreKtx = "1.7.0"
    const val lifecycle = "2.4.1"
    const val googleMaps = "3.1.0-beta"
    const val mapKtx = "2.2.0"
    const val coroutineCore = "1.5.2"
    const val coroutine = "1.6.0"
    const val composeVersion = "1.1.0-alpha06"
    const val composeActivity = "1.4.0"
    const val hiltVersion = "2.40.5"
    const val daggerCompilerVersion = "2.40.5"
    const val hiltLifecycleVersion = "1.0.0-alpha03"
    const val hiltCompilerVersion = "1.0.0"
    const val hiltNavigationComposeVersion = "1.0.0"
    const val mapsPlayServiceVersion = "17.0.1"
    const val retrofitVersion = "2.9.0"
    const val retrofitConverterVersion = "2.9.0"
    const val kotlinJdkVersion = "1.6.10"
    const val fragmentVersion = "1.4.1"
    const val navigationComposeVersion = "2.4.1"
    const val volleyVersion = "1.2.1"
    const val gradlePlugin = "2.40.5"
    const val gradle = "7.0.4"
}